# Use root/example as user/password credentials
version: '3.1'

services:
  enginedb:
    container_name: enginedb
    image: mariadb:10.4.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminadmin1
      MYSQL_DATABASE: enginedb
      TZ: Asia/Bangkok
    volumes:
      #      - ./mysql:/var/lib/mysql
      - /d/temp/mariadb:/tmp
    ports:
      - 3306:3306
    networks:
      - enginenet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.0
    container_name: phpmyadmin
    restart: always
    environment:
      TZ: Asia/Bangkok
    ports:
      - 18080:80
    volumes:
      - /sessions
    links:
      - enginedb:db
    networks:
      - enginenet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      TZ: Asia/Bangkok
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - enginenet

  engine_kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    container_name: engine_kibana
    environment:
      ELASTICSEARCH.HOSTS: "http://elasticsearch:9200"
    ports:
      - 5601:5601
    networks:
      - enginenet

  kafkadev:
    container_name: kafkadev
    image: taggdev/kafka:1.0
    environment:
      ADVERTISED_HOST: localhost
      ADVERTISED_PORT: 9092
    ports:
    - 2181:2181
    - 9092:9092

networks:
  enginenet:
    driver: bridge