# Use root/example as user/password credentials
version: '3.1'

services:
  enginedb:
    container_name: enginedb
    image: mariadb:10.4.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminadmin1
      MYSQL_DATABASE: enginedb
      TZ: Asia/Bangkok
    volumes:
      #      - ./mysql:/var/lib/mysql
      - /d/temp/mariadb:/tmp
    ports:
      - 3306:3306
    networks:
      - enginenet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.0
    container_name: phpmyadmin
    restart: always
    environment:
      TZ: Asia/Bangkok
    ports:
      - 18080:80
    volumes:
      - /sessions
    links:
      - enginedb:db
    networks:
      - enginenet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: elasticsearch
    restart: always
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      TZ: Asia/Bangkok
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - enginenet

  engine_kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    container_name: engine_kibana
    restart: always
    environment:
      ELASTICSEARCH.HOSTS: "http://elasticsearch:9200"
    ports:
      - 5601:5601
    networks:
      - enginenet

  console2es-local:
    image: tsm-registry-01.true.th:5000/mse/fluentd-console2es:1.0
    container_name: console2es-local
    deploy:
      mode: global
      resources:
        limits:
          memory: 512M
    ports:
      - 24224:24224
#      - target: 24224
#        published: 24224
#        protocol: tcp
#        mode: host
#      - target: 24225
#          published: 24225
#          protocol: tcp
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Bangkok
      FLUENTD_CONF: fluentd-console.conf
#      ES_HOSTS: http://10.95.108.206:9200,http://10.95.108.207:9200,http://10.95.108.208:9200
      ES_HOSTS: "http://10.37.219.212:9200"
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

  kafkadev:
    container_name: kafkadev
    image: taggdev/kafka:1.0
    restart: always
    environment:
      ADVERTISED_HOST: localhost
      ADVERTISED_PORT: 9092
    ports:
    - 2181:2181
    - 9092:9092

networks:
  enginenet:
    driver: bridge