version: '3.7'

services:
  tagg_mariadb:
    container_name: tagg_mariadb
    hostname: tagg_mariadb
    image: mariadb:10.5.9
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminadmin1
      MYSQL_DATABASE: enginedb
      TZ: Asia/Bangkok
    volumes:
      - /d/temp/mariadb:/tmp
    ports:
      - 3306:3306
    networks:
      - tagg_net

  tagg_phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.0
    hostname: tagg-phpmyadmin
    container_name: tagg_phpmyadmin
    restart: "no"
    environment:
      TZ: Asia/Bangkok
    ports:
      - 18081:80
    volumes:
      - /sessions
    links:
      - tagg_mariadb:db
    networks:
      - tagg_net

  #  tagg_elasticsearch:
  #    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
  #    container_name: tagg_elasticsearch
  #    hostname: tagg-es
  #    restart: no
  #    environment:
  #      discovery.type: single-node
  #      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  #      TZ: Asia/Bangkok
  #    ports:
  #      - 9200:9200
  ##      - 9300:9300
  #    networks:
  #      - enginenet
  #
  #  tagg_kibana:
  #    image: docker.elastic.co/kibana/kibana:7.5.1
  #    hostname: tagg-kibana
  #    container_name: tagg_kibana
  #    restart: no
  #    environment:
  #      ELASTICSEARCH.HOSTS: "http://microengine_elasticsearch:9200"
  #      TZ: Asia/Bangkok
  #    ports:
  #      - 5601:5601
  #    networks:
  #      - enginenet
#
#  tagg_kafka:
#    container_name: tagg_kafka
#    hostname: tagg-kafka
#    image: taggdev/kafka:1.0
#    restart: always
#    environment:
#      ADVERTISED_HOST: localhost
#      ADVERTISED_PORT: 9092
#      TZ: Asia/Bangkok
#    ports:
#      - 2181:2181
#      - 9092:9092

networks:
  tagg_net:
    driver: bridge